### ISSUE TITLE
Julia's StaticArrays contains unsafe code

### ISSUE THREAD

**Issue by radekm** [jinyus/related_post_gen#194]
Hi,

it seems that Julia solution uses `StaticArrays.jl` package which uses unsafe code https://github.com/JuliaArrays/StaticArrays.jl/blob/d80455d2e1aba57a6cf65cc8d787dc6474ec3980/src/MArray.jl#L25

Honestly my understanding of the source of the package is rather poor
so maybe the unsafe part is not called in the solution.

But if the unsafe part is called then it probably violates the rules.

**Comment by jinyus** [comment]
Thanks for reporting this. This will need to be rectified. @algunion @Moelf @LilithHafner

**Comment by algunion** [comment]
> But if the unsafe part is called then it probably violates the rules.

Thanks.

Checking this out and if confirmed (e.g. called) we'll do a PR ASAP.

**Comment by Moelf** [comment]
https://github.com/JuliaArrays/StaticArrays.jl/blob/d80455d2e1aba57a6cf65cc8d787dc6474ec3980/src/MArray.jl#L21

It checks bounds right here. It's just manually doing so because this is a low level implementation for small vector which has size information in type parameters

**Comment by jinyus** [comment]
I'm still inclined to disallow it just to be fair to the other languages.

**Comment by algunion** [comment]
> ... and then run unsafe code (because CPU instructions don't know about bounds).

Is that _unsafe_ going against the rule that states to avoid?

> [Unsafe code blocks](https://github.com/jinyus/related_post_gen#no)

From what I see, we have there two elements: 

1. the bounds check (check :) ) 
2. the unsafe code block issue (not yet clarified if it goes against the spirit of the rules)

Now, I think it is practically _safe_ - in the manner that the said _unsafe_ code is used in conjunction with `GC.@preserve`.

**Comment by algunion** [comment]
> I'm still inclined to disallow it just to be fair to the other languages.

I agree that it is important to be fair - because if the Rust implementation brings the unsafe stuff to the surface will clearly dominate this.  However, please let this exchange go on for a bit so we can reach some conclusion (and also give you more information to make a good decision).

**Comment by jinyus** [comment]
The v guys tried to do something similar...technically safe code in an unsafe context and it was disallowed. https://github.com/jinyus/related_post_gen/pull/46

**Comment by Moelf** [comment]
@jinyus Julia itself is implemented with Julia and in turn also contains unsafe calls, I think as all the checks are in place it's not having some kind of illegal advantage other than it's just how the implementation works

**Comment by Moelf** [comment]
I'm not seeing the v code doing runtime dynamic size check. This code here checks index value in bounds at run time for each and every access

**Comment by Moelf** [comment]
notice the unsafe call is guarded also by a check, too make sure the memory layout is safe to do the unsafe call. I mean if you look closely in Julia itself, at some point you just have to use low level primitive to make things happen.

The key, I would argue, is if the runtime assumes we did everything correctly vs. actually check. Here Julia is checking everything instead of assuming anything

**Comment by algunion** [comment]
@jinyus, maybe a good solution would be to try to use a more practical definition for what _unsafe_ means in practice regarding the rules of this benchmark.

I understand that given Julia's nature, some _unsafe_ magic label might just mean low level: for example, building a mutable container that is stored on a stack instead of the heap (which is _safe code in a safe context_).

So I think we need to somehow make sure we are fair to other languages but at the same time not punish Julia just because it is transparent.

**Comment by jinyus** [comment]
This will not be permitted. The rationale is that for bitstypes, bounds checking will be bypassed.

In this case, `maxv` and `maxn` are comprised of bitstypes, therefore the section of the code is specifically designed to optimize vectors containing bitstypes.

```julia
 if isbitstype(T)
        return GC.@preserve v unsafe_load(Base.unsafe_convert(Ptr{T}, pointer_from_objref(v)), i)
    end
 getfield(v,:data)[i]
```

**Comment by mkitti** [comment]
The bounds check is directly above the code.

https://github.com/JuliaArrays/StaticArrays.jl/blob/d80455d2e1aba57a6cf65cc8d787dc6474ec3980/src/MArray.jl#L21

**Comment by jinyus** [comment]
> The bounds check is directly above the code.
> 
> https://github.com/JuliaArrays/StaticArrays.jl/blob/d80455d2e1aba57a6cf65cc8d787dc6474ec3980/src/MArray.jl#L21

The rule also forbids disabling standard runtime checks, not just bounds checking.

**Comment by mkitti** [comment]
Is the rule is that we cannot do unchecked memory access even though we explicitly perform the check immediately before?

This package is cited directly in the official base language docs:
https://docs.julialang.org/en/v1/manual/performance-tips/#Consider-StaticArrays.jl-for-small-fixed-size-vector/matrix-operations

**Comment by jinyus** [comment]
I have replaced MVector with regular Vector until a consensus is reached as I need to update the results to include d and c++
https://github.com/jinyus/related_post_gen/commit/055cd395c182f430786e19aa15c9c2e2132f1c0c

**Comment by jinyus** [comment]
> Is the rule is that we cannot do unchecked memory access even though we explicitly perform the check immediately before?

I see 2 possible violations. The use of an unsafe context and bypassing any standard runtime check. Surely bounds check is not the only check performed by Julia on array access.

**Comment by jdiaz97** [comment]
Excited to see the merge of that PR!
@mkitti

**Comment by MasonProtter** [comment]
This is pretty silly. Literally ever language has unsafe internals. At some point, raw pointers are going to be interacted with at some level of abstraction. No runtime checks are omitted here. 

Here is the code being complained about:
```julia
@propagate_inbounds function getindex(v::MArray, i::Int)
    @boundscheck checkbounds(v,i)
    T = eltype(v)

    if isbitstype(T)
        return GC.@preserve v unsafe_load(Base.unsafe_convert(Ptr{T}, pointer_from_objref(v)), i)
    end
    getfield(v,:data)[i]
end
```
What this says is 
1. in the case where the compiler is unable to mathematically prove that the index `i` is inbounds, perform a runtime boundscheck to make sure that `i` is in `eachindex(v)`.
2. if the element-type is an `isbits` type, load an object of type `T` (the element type of the array) from the array's pointer at offset `i`.

**Comment by Moelf** [comment]
@jinyus btw
>I have replaced MVector with regular Vector until a consensus is reached as I need to update the results to include d and c++

https://github.com/jinyus/related_post_gen/blob/14d1b33831a0f610cc7180901b6c2a454479cc7f/cpp/main.cpp#L92

shouldn't C++ be illegal at all? I'm joking here, but C++ indexing doesn't have bound check at all right? I think we all agree the C++ code is fine because it's doing
```julia
for i in eachindex(v)
    @inbound v[i]
end
```

and in a sane language, the `@inbound` is not needed, because the compiler will figure it out.

The spirit of this rule (I think), is that you're not relying on values of the index being "correct" because programmers knows its correct. Not "do a literal search of keyword like unsafe or inbound in all non-stdlib source code"

**Comment by Moelf** [comment]
@jinyus if the line is "is this unsafe included in the language or not", then Go-lang is also illegal because the go-json uses `unsafe` pointers:

https://github.com/goccy/go-json/blob/8e8cdeacf2f2faef082f32848138f0f9af7cfb66/internal/decoder/string.go#L391-L399

**Comment by algunion** [comment]
> Go-lang is also illegal because the go-json uses `unsafe` pointers

But I don't thing that is used in the benchmark call - so I think is reasonable to accept _usafe_ as long as it is not impacting the benchmark results.

**Comment by DrBlury** [comment]
@Moelf the json package goccy was removed and is no longer in use. We now use the outdated original json package from the stdlib

**Comment by mkitti** [comment]
Friends, we're doing that thing again where we pile on. Let's take a step back.

**Comment by LilithHafner** [comment]
I think the Julia folks are being kind of silly here. If there rules say no `@inbounds` in package code, then we don't use `@inbounds` in package code. The ecosystem should be tying to move away from `@inbounds` anyway because it prevents constant-folding. It's a fun exercise. Maybe try using `Tuple`s instead?

**Comment by mkitti** [comment]
> Maybe try using `Tuple`s instead?

We have not invoked `@inbounds`. We are trying to use tuples via StaticArrays.jl, but that uses some `unsafe_*` functions to generally mutate `N` length tuples.

**Comment by StefanKarpinski** [comment]
I'm going to chime in here with what other people have already said, perhaps expressed a different way. What exactly is the criterion here? If the criterion is that benchmarks are not allowed to use functionality that is internally implemented with unsafe constructs, then you should delete the entire repo because everything in every language is ultimately implemented in terms of unsafe constructs? If the criterion is that benchmarks must use APIs that cannot be used in unsafe ways, then there's no reason to not use StaticArrays because they are, in fact safe, despite the _internal_ use of unsafe methods.

@jinyus, can you clarify what the actual rule for the benchmarks is?

**Comment by Moelf** [comment]
I think if `StaticArrays.jl` is a std-lib or built-in module it would have been fine, if I'm reading this correctly

**Comment by dlakelan** [comment]
IMHO a good rule would be "code written for the benchmark itself doesn't use unsafe constructs and must not use some silly public package created just to package needed code for this benchmark". This means you could call any public packages in the general ecosystem but you couldn't write `@inbounds` or directly call `unsafe_*` within the benchmark code. Presumably this mimics what would be done in reality in a programming team at a company or a free software project where there was a policy not to have the team write unsafe code, but using libraries with safe APIs would be allowed regardless of how they're implemented underneath the API.

**Comment by DrBlury** [comment]
@StefanKarpinski 

### I am not the owner/maintainer of this repo so I can only give you a personal opinion here. But it may be what @jinyus wanted. 

**If your stdlib uses unsafe code, that's fine**. If you use another external package that wants you to use unsafe, that's not OK. **The code for the benchmark itself should also be safe.** 
_Best use the language as it's supposed to._ 

_If you don't have a json package and need to parse json files in your code, then by all means use the package that's available to you. (Even though the I/o time no longer counts)._ 

But in regards to the compute... 
Do not use custom packages/code that are unsafe, just for the performance increase in this benchmark. Use a generalised approach to your code. Do not customise for the specifics of this benchmark, make reasonable assumptions as you would IRL and you're good to go!

**Comment by DrBlury** [comment]
@dlakelan **is there a safe alternative to do this that's also popular and is not using unsafe code?** 
_If so, go with that, if not... I'm not here to decide but I think as it's not officially stdlib, it'll have to go._ 

I could also go crazy with CGO in the go project but I think during the compute phase that's measured, we should all stick to safe operations and no wacky solutions. 

_Although - and I give you that - in Julia it looks quite good to me._ 
There for sure are similar unsafe packages for other languages that are not used yet.

**Comment by MasonProtter** [comment]
It's not unsafe. Every access to it is guarded by a boundscheck.

**Comment by cdsousa** [comment]
Julia's StaticArrays.jl is the standard "go to" lib for fixed-size arrays!

It is much safer than C++'s stdlib for fixed-size arrays, `std::array`, that compiles and runs this code:

```c++
#include <iostream>
#include <array>
int main() {
    std::array<int, 5> a = {1,2,3,4,5};
    std::cout << a[10];
    return 0;
}
```

(Yes, I know that one can use `.at(10)` for bounds checking, but that's not enforced.)

**Comment by JeffBezanson** [comment]
It doesn't seem right for this decision to hinge entirely on whether a certain package is considered part of the stdlib. It's not *good* to have a huge stdlib, and what's included is ultimately pretty arbitrary. This comment captures my view perfectly: https://github.com/jinyus/related_post_gen/issues/194#issuecomment-1759981528

**Comment by algunion** [comment]
> we should all stick to safe operations and no wacky solutions.

@DrBlury, Exactly: that is what we did with `StaticArrays`.

Also, it is not wacky or unsafe at all - any Julia user who goes over the manual might encounter [this ](https://docs.julialang.org/en/v1/manual/performance-tips/#Consider-StaticArrays.jl-for-small-fixed-size-vector/matrix-operations)at some point:

> If your application involves many small (< 100 element) arrays of fixed sizes (i.e. the size is known prior to execution), then you might want to consider using the [StaticArrays.jl package](https://github.com/JuliaArrays/StaticArrays.jl). This package allows you to represent such arrays in a way that avoids unnecessary heap allocations and allows the compiler to specialize code for the size of the array, e.g. by completely unrolling vector operations (eliminating the loops) and storing elements in CPU registers.

In a way, if you have a bloated STDLIB with lots of unsafe code, you are gonna fare better than those languages with a philosophy of a think stdlib.

I was initially attracted to this benchmark because it seems to resemble what you would do in a real-world project if you need to extract as much speed as you can using what you have at hand in the language ecosystem.

However, this has become more like - _if you have a go-to library in your language ecosystem, you need to make sure you know all the implementation details before using it_ (even if it is battle-tested and the standard approach for an entire community).

So, we ended up with a solution that would not actually reflect a real-life idiomatic Julia solution (if performance is needed to any extent). But since it is a benchmark, performance is implied. 

Anyway, @jinyus, as the owner, can set whatever rules he wants. But I completely lost interest as this is no longer a real-life scenario since the developer is prohibited from using the one library that would actually pick in real life.

Also - at some point somebody tried to fill in the gap of banning `StaticArrays` and his answer was:
> Making a specialized, fixed size array definitely goes against the spirit of the competition and other solutions will mimic this to level the playing field.

So you cannot use the go-to package that you would use in real life - and when you try to replace the missing functionality (without breaking the unsafe-related rules), you are actually still breaking the spirit of the competition.

I have no idea what the spirit of the competition is supposed to be then: but I am certain that this is no longer a real-world scenario.

**Comment by DrBlury** [comment]
@arikheinss Brilliant, I agree!

**Comment by jinyus** [comment]
@arikheinss Even if I should disregard the rule that bans unsafe contexts. The code violates another rule which bans bypassing standard runtime checks, **not** just bounds checks. 

The code plucks the integer directly from memory, thus, bypassing all other runtime checks that Julia would do otherwise...which is why it only works for bittypes.

**Comment by arikheinss** [comment]
I don't get what you mean. Do you mean the number of related posts should not be hardcoded into the soulustion, but remain variable?

**Comment by Moelf** [comment]
>The code plucks the integer directly from memory, thus, bypassing all other runtime checks that Julia would do otherwise...which is why it only works for bittypes.

the `bittype` is the only safe check you need here. Just like "bounds check manually followed by inbounds access should be legal", this should be legal and again, this is really a natural thing for any Julia package to do -- using a well established package for small fixed-size vector

**Comment by Moelf** [comment]
here's another demonstration to show it's really safe due to runtime check -- we use random length and random index:

```julia
julia> function main()
           l = rand(1:10)
           idx = rand(1:10)
           a = @MVector zeros(l)

           @show l, idx
           return l[idx]
       end
main (generic function with 1 method)

julia> main()
(l, idx) = (8, 10)
ERROR: BoundsError: attempt to access Int64 at index [10]
Stacktrace:
 [1] getindex
   @ Main ./number.jl:98 [inlined]
 [2] main()
   @ Main ./REPL[7]:7
 [3] top-level scope
   @ REPL[8]:1

julia> main()
(l, idx) = (6, 1)
6
```

**Comment by Seelengrab** [comment]
> The code violates another rule which bans bypassing standard runtime checks, not just bounds checks.

To not get bogged down in what assembly exactly runs, as I've asked above, could you elaborate on which "standard runtime checks" are omitted? I think there's a mismatch between our models in how Julia works/operates.

**Comment by StefanKarpinski** [comment]
> @DrBlury: **If your stdlib uses unsafe code, that's fine**. If you use another external package that wants you to use unsafe, that's not OK.

This isn't really a good place to draw the line IMO, since what is or is not called "stdlib" is pretty arbitrary. Stdlibs in Julia are just packages that happened to be shipped with the Julia binary and in some cases (but not all) baked into the binary that you run; there are other stdlibs that aren't baked in and which you can load not at all or load a different version of. More generally, there's nothing special about built-in types. A lot of really basic types are defined in Julia, like `Int8`, `Float64`, and so on; there's ongoing work to change the "built in" `Array` type to be defined in Julia as well, in terms of lower level (unsafe) constructs. Some languages build all these things into the language and don't give you a way to do it yourself, others implement very small primitives and then let you bootstrap everything from there. There's been discussion of making `StaticArrays` into a stdlib and there's no reason it couldn't be one, aside from the fact that it doesn't have to be one.

I think a more reasonable place to draw the line would be for the benchmark code not to use unsafe APIs. So, using `@inbounds` for example would not be allowed. Which brings us to...

> @jinyus: Even if I should disregard the rule that bans unsafe contexts. The code violates another rule which bans bypassing standard runtime checks, not just bounds checks.
>
> The code plucks the integer directly from memory, thus, bypassing all other runtime checks that Julia would do otherwise...which is why it only works for bittypes.

There seems to be a misunderstanding here. `StaticArrays` works fine for all kinds of types, not just bitstypes:
```jl
julia> using StaticArrays

julia> MVector{3}([["foo"], ["bar"], ["baz"]])
3-element MVector{3, Vector{String}} with indices SOneTo(3):
 ["foo"]
 ["bar"]
 ["baz"]

julia> SVector{3}([["foo"], ["bar"], ["baz"]])
3-element SVector{3, Vector{String}} with indices SOneTo(3):
 ["foo"]
 ["bar"]
 ["baz"]

julia> mutable struct X
           f::Int
       end

julia> SVector{3}([X(1), X(2), X(3)])
3-element SVector{3, X} with indices SOneTo(3):
 X(1)
 X(2)
 X(3)
```
Sure, it "plucks the integer directly from memory" but so does any API in any language that loads an integer from a data structure. StaticArrays does all the necessary checks to make this fully safe:

1. It does a bounds check (and there's no TOCTOU issue since MArrays cannot be resized)
2. It makes sure the object cannot be garbage collected before it is loaded by using `@GC.preserve`

This is exactly the same way it would be implemented if `StaticArrays` were built into the language and just as safe to use.

**Comment by cyrusmsk** [comment]
There is another option:
You can ask to make top{N} algo, where N will be defined in the input file or parameter. In that case N will not be available in the compile-time.
So run of the bench will be like "./applicaion 10" - and it will ask to calculate top10 statistics.

**Comment by Moelf** [comment]
>You can ask to make top{N} algo, where N will be defined in the input file or parameter. In that case N will not be available in the compile-time.

yeah that's totally fine,`MVector{}` can be constructed using a run-time length

**Comment by cyrusmsk** [comment]
> > You can ask to make top{N} algo, where N will be defined in the input file or parameter. In that case N will not be available in the compile-time.
> 
> yeah that's totally fine,`MVector{}` can be constructed using a run-time length

Will it be still stack allocation?

**Comment by MasonProtter** [comment]
This is irrelevant to the topic at hand, but yes it will be stack allocated, there'll just be a dynamic dispatch.

**Comment by cyrusmsk** [comment]
Then in case author will decide to use N for topN as a parameter I suppose it should be added to the rules "not allocate on stack in that case". Because this is was the idea of why to make N dynamic. Just to eliminate this part of the difference of languages from comparison.
Otherwise it could create another difference and not solve anything : some will allocate in heap and the others on stack..

**Comment by MasonProtter** [comment]
Why?

**Comment by StefanKarpinski** [comment]
Where something is allocated is generally not part of language semantics and compilers are free to choose stack or heap depending on what they can prove and what they deem better. So that seems like a non-starter requirement. But making N a runtime parameter does seem like a good idea. But as mentioned here it doesn't prevent using StaticArrays.

**Comment by DrBlury** [comment]
But if we make topN dynamic, Julia will benefit from it's JIT warmup in the first call. (I think) I do now know the internals of Julia so please correct me if i'm mistaken here.

Compiled languages would be at a disadvantage then if we allow warmup for JIT languages so they can use a static array during runtime but pre calculation.

What do you people think?

**Comment by Imperatorn** [comment]
> But if we make topN dynamic, Julia will benefit from it's JIT warmup in the first call. (I think) I do now know the internals of Julia so please correct me if i'm mistaken here.
> 
> Compiled languages would be at a disadvantage then if we allow warmup for JIT languages so they can use a static array during runtime but pre calculation.
> 
> What do you people think?

Interesting observation

**Comment by Moelf** [comment]
>What do you people think?

sure but it wasn't a Julia person proposing it... it was just a hypothetical question I guess.

The last main question from this thread is still not addressed and I don't think repo owner wants to say much more so I guess there isn't much of a point in continuing on tangents

**Comment by Imperatorn** [comment]
We must have some rules, because otherwise everything could be done at compile time and the time would become 0 s, at least for those languages that have it.

**Comment by Moelf** [comment]
yes but can we stop going on a tangent? If possible I still want to hear response to:

- https://github.com/jinyus/related_post_gen/issues/194#issuecomment-1760178144
- https://github.com/jinyus/related_post_gen/issues/194#issuecomment-1762118650

regarding "stdlib" is just arbitrary so we should be able to use `StaticArrays.jl` which is implemented "just as a stdlib would have implemented", as two of the Julia co-creators agree.

**Comment by DrBlury** [comment]
I agree that stdlib is pretty arbitrary. I should have made myself clear, I meant more widely used packages that are well established in the ecosystem. But during this conversation I accepted that other languages follow other philosophies so i'm not the one to argue your code/lib choices. Choose whatever you want.

But that's just my opinion though. 

If i were a julia committer to this repo id probably just do the following:

Set up the project in a way that I don't need a warmup call to compile all paths (someone said this would be possible). Then just use static array with the @inbounds macro as it seems like it's the same check that's done otherwise.

For me that would be fine. But i'll repeat myself here, i'm not the maintainer/owner, just a committer here.

**Comment by cyrusmsk** [comment]
At least StaticArray is not alone. Smallvec from Rust also under consideration. https://github.com/jinyus/related_post_gen/pull/244

**Comment by Moelf** [comment]
Yes, and I believe package behind

https://github.com/jinyus/related_post_gen/blob/d4d4fd153e039530934f6115d2bf292805bf36fa/rust/src/main.rs#L80

Contains unsafe code?

**Comment by Imperatorn** [comment]
I think in general every language should try to write as close to "normal" code as possible while following the rules.

It's hard to make the rules specific enough of course. Like I said previously, nothing should be allowed to "warm up" or be done at compile time, since then for D for example we could just do everything at compile time and have a 0 second program 😅

**Comment by Moelf** [comment]
That's precisely why we used StaticArrays.jl, it's recommend in official documentation for this use case and one can easily check its widely used in the whole Julia ecosystem

**Comment by Imperatorn** [comment]
As much of stdlib as possible is maybe a good guiding principle?

**Comment by Moelf** [comment]
in case you didn't real, Julia deliberately want to make things not stdlib, it has been moving things OUT OF stdlibs for a while now, and continue doing so

**Comment by schveiguy** [comment]
I think functions that use unsafe primitives with a safe interface is what it's all about. For example, D uses C stdio, which uses `read(void * data, size_t length)`. There is no way at all to say that `read` is safe. But you can have a safe interface to it, as long as the language has a *concept* of a pointer/length pairing, and an insistence either via compile-time checks or runtime checks that you cannot do this for things containing pointers. So in D, we have `file.rawRead(ubyte[] arr)` to achieve this.

If Julia has a safe interface to a stack-allocated array, it should be allowed as long as it can be proven the calls to index are checked at runtime or compile time. It looks to me like it is doing both of these things, and it would be a disservice to Julia submissions to prevent them from using the language the way it was intended. Using stack arrays is a fabulous speedup, and absolutely can be done in a safe way. And most optimizers will even remove unnecessary bounds checks if it knows the index is within bounds at compile time.

Now I *kind of* get the viewpoint that there are tricks that can be used to circumvent safety checks, and you don't want to allow those. But I would say as long as it's behind a safe *interface*, and it can be proven the underlying code that uses unsafe tricks is sound (i.e. the bounds are checked outside a loop that knows the semantics of the indexing), it should be allowed. I realize there is not any desire to go around policing every language and every library, so maybe you just have to make some non-perfect rules like how established a package is? It sounds like this package is meant to be part of the language. I would vote to let it pass.

**Comment by algunion** [comment]
> If Julia has a safe interface to a stack-allocated array, it should be allowed as long as it can be proven the calls to index are checked at runtime or compile time. It looks to me like it is doing both of these things, and it would be a disservice to Julia submissions to prevent them from using the language the way it was intended.

🎯

**Comment by cyrusmsk** [comment]
Maybe you can kindly allow to use such kind of libraries @jinyus ?
I think it will be fair for everyone (even if it is not in my interest as of contributor of D solution, and I'm not related to Julia community). Using stack allocated small arrays is quite common practice, and probably we shouldn't penalized languages which don't have it in their std. Of course the library should be mature and robust, but it seems it is exactly the case for Julia's library.

**Comment by algunion** [comment]
@jinyus - just a friendly reminder about the messages exchanged above.

Obviously, you are not forced to do anything - you are _whatever kind you want_ dictator of this repository.

I sincerely do not think you are unfair in an ill-intended way. 

However, I want to point out the following:
- two of the Julia creators attended this thread and participated with reasonable explanations about the relationship between specific packages and Julia's stdlib (e.g. `StaticArray` is a battle-tested and _de facto_ stdlib component - the only difference is a semantic/arbitrary quirk.
- it was clearly pointed out that your conclusion  _[disregards all other runtime checks](https://github.com/jinyus/related_post_gen/issues/194#issuecomment-1758848934)_ is actually not reflecting the package reality.
- we even have non-Julia contributors to the repository who understood the state of the Julia ecosystem well enough to actually agree that the usage of the `StaticArrays` package is not in violation of the rules and given that it is also the _go to_ package, it is not used in an unfair way only to gain some competitive advantage.

As I said, I do not think you are ill-intended, but I do think that it is unfair not to allow `StaticArrays` usage in the standard Julia implementation.

A satisfying solution for me to look over this thread in good faith and make a final decision. Please provide an updated reasoning if you still want to maintain the `StaticArrays` prohibition.

Cheers.
