### ISSUE TITLE
D implementation

### ISSUE THREAD

**Issue by ilevd** [jinyus/related_post_gen#240]
It's interesting to see max scores of performant versions, but if there are rules, I think all implementations should follow them. Also in some languages there are really simple tricks to speedup processing with adding literally or almost no additional line of code.

So, It seems that in D implementation instead of
```
taggedPostsCount.ptr[idx]++;
```
should be: 
```
taggedPostsCount[idx]++;
```
It's relative both to [d](https://github.com/jinyus/related_post_gen/blob/b8f79171cc6849260fe62cd90a3aea8f631f8803/d/source/app.d#L52C5-L52C33) and [d_con](https://github.com/jinyus/related_post_gen/blob/b8f79171cc6849260fe62cd90a3aea8f631f8803/d_con/source/app.d#L55) implementations.

https://dlang.org/blog/2016/09/28/how-to-write-trusted-code-in-d/

But it would be nice to have some notes in Readme or maybe additional comment column or row in the table with such results.

**Comment by Imperatorn** [comment]
We can change that if you want, didn't make much of a difference

**Comment by cyrusmsk** [comment]
Yeah If it is violating rules - let's remove this part

**Comment by Imperatorn** [comment]
> It's interesting to see max scores of performant versions, but if there are rules, I think all implementations should follow them. Also in some languages there are really simple tricks to speedup processing with adding literally or almost no additional line of code.
> 
> So, It seems that in D implementation instead of
> 
> ```
> taggedPostsCount.ptr[idx]++;
> ```
> 
> should be:
> 
> ```
> taggedPostsCount[idx]++;
> ```
> 
> It's relative both to [d](https://github.com/jinyus/related_post_gen/blob/b8f79171cc6849260fe62cd90a3aea8f631f8803/d/source/app.d#L52C5-L52C33) and [d_con](https://github.com/jinyus/related_post_gen/blob/b8f79171cc6849260fe62cd90a3aea8f631f8803/d_con/source/app.d#L55) implementations.
> 
> https://dlang.org/blog/2016/09/28/how-to-write-trusted-code-in-d/
> 
> But it would be nice to have some notes in Readme or maybe additional comment column or row in the table with such results.

I have removed the .ptr part. You might be right that it's against the rules.

**Comment by algunion** [comment]
Also, some memory allocation seems to occur before the timer starts. That is not OK.

![image](https://github.com/jinyus/related_post_gen/assets/3482227/ea517531-944f-46e5-b1a3-ac0341012d7b)

**Comment by jinyus** [comment]
fix pointer: https://github.com/jinyus/related_post_gen/commit/498a77bd8185ddd31cc9ac1c1b53cf8f09ee5791
fix mem alloc: https://github.com/jinyus/related_post_gen/commit/b57ee19497a4609341d4604b2778186ced94521d

**Comment by algunion** [comment]
Also - a nice thing: D uses static arrays (which I totally agree is the way to go). But it happens to have them in the stdlib - if somehow, for any reason, D decides to make the static array a standalone package - this D implementation would likely be forbidden for reasons of _unsafe_ being used in the static arrays implementation.

Anyway - the _nice_ thing is that some communities can just go and implement the sensible thing they would also do in real life - while others are forbidden to go that path.

To some extent - and for some languages - this benchmark sounds like _give us the implementation that you would not actually use in real life so we can report performance statistics that are not representative of your language_. 

Hey - but everything goes: because the owner of the repo has unlimited powers - and he is unlikely to be convinced even by the well-crafted [arguments ](https://github.com/jinyus/related_post_gen/issues/194#issuecomment-1762118650)of Julia's creators.

**Comment by Imperatorn** [comment]
> fix pointer: [498a77b](https://github.com/jinyus/related_post_gen/commit/498a77bd8185ddd31cc9ac1c1b53cf8f09ee5791) fix mem alloc: [b57ee19](https://github.com/jinyus/related_post_gen/commit/b57ee19497a4609341d4604b2778186ced94521d)

Thanks 🙏
