### ISSUE TITLE
PGO effect [.NET, Nim]

### ISSUE THREAD

**Issue by cyrusmsk** [jinyus/related_post_gen#263]
In .NET8 - TieredPGO enabled by default (https://devblogs.microsoft.com/dotnet/announcing-dotnet-8-preview-5/)

I’m wondering which effect it gave to the code of this benchmark?
Can someone run it with/without option in settings:
<TieredPGO>false</TieredPGO>

Also interesting how big is effect for Nim.

**Comment by inv2004** [comment]
@cyrusmsk 
Affect in Nim is pretty big:
clang without PGO: 25ms
gcc (no PGO): 18ms
clang with PGO: 17ms (-32%)

**Comment by michaelsbradleyjr** [comment]
I was about to write that I've observed even bigger differences, BUT.......

There have been a number of changes in the Nim impl recently. *Before* the introduction of `fixedtable` and some other refactoring by @inv2004, also `proc` -> `func` where appropriate, I saw non-optimized runs 4x longer than PGO runs. *After* those changes, I'm now realizing that PGO is barely affecting the performance, at least on my machine.

So now I'm conflicted about it because I don't like stuff in the mix that's like *"🤞 it will make a difference"* if the wind is blowing the right direction and my coffee cup is just far enough away from my laptop"*. 😅

**Comment by cyrusmsk** [comment]
Also one more thing maybe to make task more "real world": add several input files to the directory. Let's say 5: [posts_1.json, posts_2.json, ..}.
After that languages with PGO/warmup could use posts.json for that. But for time measuring before open the file code will make random choice from i=1..5 and open "posts_i.json" for bench.

Because right now absolutely the same file for Warm-up/PGO is used, which is not looking like "real world problem" case.
@jinyus

**Comment by jinyus** [comment]
@cyrusmsk  that could be addressed by only sending 1 item during the warmup stage and for PGO solutions, only compile once...that should save some time too.

**Comment by Imperatorn** [comment]
D doesn't use any PGO atm
