### ISSUE TITLE
[Question] process of running benchmark

### ISSUE THREAD

**Issue by inv2004** [jinyus/related_post_gen#344]
Can someone explain:
- how it runs?
 Is it just external azure server with runs docker or remote github runner?
- does it use docker runner images?
- where to get the images (docker images?) to check locally?
- does it follow github workflow yml or Dockerfile?
- how to run it locally in the same environment ?

Because overall process of running and checking it locally is not clear.

**Comment by michaelsbradleyjr** [comment]
I have replicated the setup (or attempted to), so I believe I can answer correctly. But if I am mistaken then it will be a good opportunity to have a correct understanding informed by the project maintainer.

> how it runs?

There's a `Standard F4s v2 (4 vcpus, 8 GiB memory)` VM in Azure, running Ubuntu 22.04.

> does it use docker runner images?
> [etc]

A container image is built in the Azure VM by running this command in the root of a clone of this project's repo, which builds per the `related_post_gen` [Dockerfile](https://github.com/jinyus/related_post_gen/blob/main/Dockerfile).
```
docker build -t databench .
```
PR branches can then be benchmarked like this
```
docker run -it --rm -e GIT_REPO='https://github.com/inv2004/related_post_gen.git' -e BRANCH='nim_gcc_again' -e TEST_NAME=nim databench
```

> how to run it locally in the same environment?

Build the container image same as above on your local computer or some VM or wherever. Then benchmark the desired branch, same as above.

**Comment by inv2004** [comment]
In the case - why the Arch build does not have the same gcc and clang
versions like it was provided here:
https://github.com/jinyus/related_post_gen/pull/338#issuecomment-1771105956
?

**Comment by michaelsbradleyjr** [comment]
> In the case - why the Arch build does not have the same gcc and clang...

Turns out it has both `clang-16` and `clang-13`, but that's not immediately obvious. I didn't realize that until a little while ago.

Before I got setup on Azure VM and built from the Dockerfile, I used some parts of it to build a container on my laptop. Starting with `docker run -it archlinux:base bash` and then commands in shell  from this part

https://github.com/jinyus/related_post_gen/blob/5e37784c6944d52087f9cd0601630175d5f27a08/Dockerfile#L7-L9

After those installs
```
$ clang --version
clang version 16.0.6
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/sbin
```

I didn't need most of the rest of it for `nim` and `nim_con` except `pip install ...`

But if build an image straight from the Dockerfile then
```
$ run -it --rm databench bash
$ clang --version
clang version 13.0.0 (https://github.com/apple/llvm-project.git 8ee3f51668ac68de50d541a815f00859f4922f98)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/builduser/swift-5.9-RELEASE-ubuntu22.04/usr/bin
```

So from the following step in the Dockerfile `clang-13` has precedence in the PATH as `clang`
https://github.com/jinyus/related_post_gen/blob/5e37784c6944d52087f9cd0601630175d5f27a08/Dockerfile#L40

**Comment by jinyus** [comment]
These are the new versions:
```
gcc (GCC) 13.2.1 20230801
clang version 16.0.6
```
@michaelsbradleyjr 
swift ships with an older clang so it was using that instead of the global version. rebuild the image to use the updated version. Should be quick as the other layers are cached
