### ISSUE TITLE
Allow .ptr if proven safe?

### ISSUE THREAD

**Issue by Imperatorn** [jinyus/related_post_gen#350]
```d
		foreach (tag; post.tags)
			foreach (idx; tagMap[tag])
				taggedPostsCount[idx]++;
```
Should be able to be replaced by

```d
		foreach (tag; post.tags)
			foreach (idx; tagMap[tag])
				taggedPostsCount.ptr[idx]++;
```

Because it's proven safe as stated by the code.

"The size of taggedPostsCount is equal to the number of posts (postsCount). Since idx is generated from indices within the posts array itself (through the tagMap), idx will always be a valid index within taggedPostsCount. As such, you won't index taggedPostsCount with an out-of-bounds value."

**Comment by Imperatorn** [comment]
Note that I am explicitly talking about out of bounds, not overflow.

taggedPostsCount can never be out of bounds by idx.

Hence I would argue that .ptr should be allowed in this case.

**Comment by michaelsbradleyjr** [comment]
Fwiw, It seems reasonable to me.

I applied similar reasoning for what I did in `nim_con` with `addr`/`ptr`/`[]`. I haven't looked at your overall code, but in `nim_con` there is additional reasoning about safety because the input array (`seq` in Nim) and tag map are immutable after they are generated, and it can be clearly reasoned from the implementation that no two worker threads will ever attempt to write to the same index in the `seq` that, after the workers are finished, is serialized to JSON on the main thread and written to disk.

**Comment by schveiguy** [comment]
FWIW, this is exactly the kind of real-world optimization that one would apply -- it's straightforward to reason about and explain in comments. I would do it in my code, because I know what care I would take to ensure it stays that way.

However, this cannot be proven at compile-time, and is very fragile. In the future, someone could mess up the storage of the indexes, and then you will have data corruption if the indexes go out of bounds. Or they might accidentally be used on the wrong array (in the concurrent version, we have a vector array which has a much smaller length).

The point of memory safety features such as bounds checks is to avoid having to check code for memory safety, even if you introduce bugs later. The rules in D are there for a reason, which means the bounds checks should stay in, unless the compiler can sleuth out that they are unnecessary (this does happen for the static arrays).

If I understand the goal of the safety requirement, I unfortunately think that .ptr cannot be acceptable in this instance. There is no specific safe interface to the code, it's just because we proved it *for that iteration of the code*.

If, however, there were a way to tie the indexing to a type, which can be proven to have a safe interface, then it should be allowed.

**Comment by jinyus** [comment]
I agree with @schveiguy
